server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # API Gateway Reverse Proxy (Unificado)
    location /api/ {
        proxy_pass http://host.docker.internal:8080/api/;
    }

    # Compatibilidad con rutas anteriores (opcional, redirigiendo al Gateway)
    location /catalog-api/ {
        proxy_pass http://host.docker.internal:8080/api/v1/;
    }
    location /orders-api/ {
        proxy_pass http://host.docker.internal:8080/api/v1/;
    }
    location /sales-api/ {
        proxy_pass http://host.docker.internal:8080/api/v1/;
    }
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
